# Generated by Django 4.1.5 on 2023-01-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='catg',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='refcode',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
